Rest 76
teamclairvoyant/restonomer pull request #31
Opened 2022-12-13 17:08 UTC by umang-clairvoyant

Column to Json transformation

2022-12-13 22:29 UTC, rahulbhatia023 commented on core/src/it/resources/mock_data/transformation/__files/mocked_column_to_json_transformation_response.json
> +}
Add new line at end of file

2022-12-13 22:33 UTC, rahulbhatia023 requested changes
Just one comment + add documentation

2022-12-14 16:49 UTC, umang-clairvoyant commented on core/src/it/resources/mock_data/transformation/__files/mocked_column_to_json_transformation_response.json
> +}
resolved

2022-12-15 14:34 UTC, rahulbhatia023 approved these changes

2022-12-15 14:39 UTC, merged